### ISSUE TITLE
global link for url and mirrors

### ISSUE THREAD

**Issue by amitchettri** [k8sre/k8s_init#14]
Hi,

Can you help with the global urls and mirrors and registry rather it been going towards aliyuncs.com, https://k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn, registry.aliyuncs.com, docker.mirrors.sjtug.sjtu.edu.cn its not accessible for me.

help or guidance would be very helpful

**Comment by kubeop** [comment]
You can modify the URL in group_vars.
