### ISSUE TITLE
清单文件建议加入python路径

### ISSUE THREAD

**Issue by cucy** [k8sre/k8s_init#23]
https://github.com/kubeop/k8s/blob/3d3db71cfb5afdadab7048e0dc07c14ab03a08e2/inventory#L1

[all:vars]
ansible_python_interpreter=/usr/bin/python3

**Comment by kubeop** [comment]
可以根据自己的环境情况添加，有些人的环境默认没有/usr/bin/python3的，所以使用默认的自动识别更合适一点

**Comment by kubeop** [comment]
这个配置也建议添加到ansible.cfg配置文件中，如果路径识别遇到问题，应该也不仅仅是部署k8s节点有问题，可能连接非k8s节点操作也有问题
