### ISSUE TITLE
Check whether the master is ready? failed

### ISSUE THREAD

**Issue by luogenhua** [k8sre/k8s_init#24]
- name: "Check whether the master is ready?"
  shell: "kubectl get node | grep {{ hostvars[item].hostname.split('-')[-2:] | join('-') | lower }}-{{ item }}"
  register: master_status
  until: '"Ready" in master_status.stdout'
  retries: 5
  delay: 3
  delegate_to: "{{ groups['master'][0] }}"
  with_items:
    - "{{ groups['master'] }}"
  tags:
    - create_master_label
    - create_master_taint
    - create_label

执行到这里的时候失败，提示no resource ，有可能是啥原因？我配置了loadbalance.ip有关系吗？

**Comment by kubeop** [comment]
可以把inventory内容和group_vars/all.yml中loadbalance段的配置贴出来看一下
